[package]
name = "usd_data_extractor"
edition.workspace = true
version.workspace = true

build = "build.rs"

[dependencies]
cxx = "1.0.121"
oneshot = "0.1.6"

[build-dependencies]
cxx-build = "1.0.121"
glob = "0.3.1"
vcvars = "0.1.6"
